### ISSUE TITLE
Ansible-Fortigate-Pyfg module/package- ERROR(config failed)

### ISSUE THREAD

**Issue by aloksrinet** [fortinet-solutions-cse/fortiosapi#10]
[ERROR-Fortigate.pdf](https://github.com/fortinet-solutions-cse/fortiosapi/files/1207699/ERROR-Fortigate.pdf)
[playbook.pdf](https://github.com/fortinet-solutions-cse/fortiosapi/files/1207700/playbook.pdf)

**ERROR(config failed)**

**Comment by mavbig** [comment]
Do you have VDOMs configured on your FortiGate?

**Comment by aloksrinet** [comment]
No i dont have...how to configure VDOMs on fortigate
