### ISSUE TITLE
UnicodeDecodeError at login

### ISSUE THREAD

**Issue by robertpenz** [fortinet-solutions-cse/fortiosapi#15]
This happens when the default system proxy gets used with does not allow the request to the fortimanager, but returns an error message page. There should be an error handing. running on Fedora 27 with python 2.7.14

```
$ python testlogin.py 
Traceback (most recent call last):
  File "testlogin.py", line 35, in <module>
    main()
  File "testlogin.py", line 28, in main
    resp = fgt.login(fgthost, user, passwd)
  File "xxxxxxx/fortinet/fortiosapi/fortiosapi.py", line 123, in login
    if res.content.decode('ascii')[0] == '1':
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5337: ordinal not in range(128)
```

**Comment by robertpenz** [comment]
even after using no proxy it didn't work - moved to https://github.com/pschmitt/fortipy, which works .

**Comment by thomnico** [comment]
Hello robertpenz,

A quick look at your code and comments seems to indicate you are targeting fortimanager this library is targeting fortios/fortigate REST API. Please confirm so that we gently close

**Comment by robertpenz** [comment]
yes, was not clear to me that fortios is not fortimanager. perhaps you update the description to make that clearer, thats its for fortigate directly but not via fortimanager. Also interesting that there is no python client lib for fortimanager directly from fortinet - or I was not able to find it ;-)
