### ISSUE TITLE
KeyError: 'vm'

### ISSUE THREAD

**Issue by ikreb7** [fortinet-solutions-cse/fortiosapi#17]
Hello,

I got the error:

    if resp['results']['vm']['status'] == "vm_valid" or "vm_eval":
    KeyError: 'vm'

But I have the firmware version 5.6.2. Any idea what could be the problem?

**Comment by mamunozgonzalez** [comment]
Hi,
 I have just tried with 5.6.2 and seems to be working fine. Can you share your code so I can have a look to it?

To give you an idea, this code works with my licensed fortigate vm:

```
#!/usr/bin/python

from fortiosapi import FortiOSAPI

FGT_HOST='192.168.122.40'
FGT_USER='admin'
FGT_PASSWORD=''


fosapi = FortiOSAPI()
fosapi.https('on')
fosapi.login(FGT_HOST, FGT_USER, FGT_PASSWORD)

print(fosapi.license())

fosapi.logout()
```

BR,
Miguel Ángel Muñoz.

**Comment by thomnico** [comment]
Hello,

Are you using this on hardware fortinet ??

**Comment by ikreb7** [comment]
Hello guys,

@mamunozgonzalez I tried your code and get the same error.

@thomnico Yes, I use a fortigate 60D (v5.6.2 build1486).

**Comment by mamunozgonzalez** [comment]
That is very strange. 
Can you check the license still valid? 
Can you print the whole error stack and messages that you get when you run the previous code?

**Comment by mamunozgonzalez** [comment]
@ikreb7 , it seems that this fails with HW appliances. With virtual VMs works fine.
I'll provide a fix as soon as possible.

**Comment by mamunozgonzalez** [comment]
@ikreb7 I generated a fix for it. It is already merged into master branch.
I'll generate a new package for pypi shortly

**Comment by mamunozgonzalez** [comment]
New version generated with the bug fixed: 
https://pypi.python.org/pypi?:action=display&name=fortiosapi&version=0.9.91
