### ISSUE TITLE
Needs timeout value

### ISSUE THREAD

**Issue by pffs** [fortinet-solutions-cse/fortiosapi#19]
Requests does not timeout without a timeout value being passed to it. Right now there isn't any mechanism to pass a timeout to the individual request calls that I can tell, so a down device can hang indefinitely (I've seen up to 15 minutes in my environment which is probably when my firewall is killing the session, but in theory requests will hang forever if you let it).

Should probably be able to define a timeout on the FortiOSAPI init and then update the various _session calls to include the timeout option.

**Comment by thomnico** [comment]
Hello,

The login method does timeout, hence I did not encounter letting the session half open and the Fortigate disappear.

You are right thought and will implement the timeout method in the requests calls soon.

Thanks for the bug

**Comment by thomnico** [comment]
Fixed in 0.10.0 version
