### ISSUE TITLE
KeyError: 'results'

### ISSUE THREAD

**Issue by ikreb7** [fortinet-solutions-cse/fortiosapi#23]
Hello, 

I get this error messege: 

```
if resp['results']['vm']['status'] == "vm_valid" or "vm_eval":
KeyError: 'results'
```

This is my example code to reproduce the error:

```
#!/usr/bin/python

from fortiosapi import FortiOSAPI

FGT_HOST='192.168.122.40'
FGT_USER='admin'
FGT_PASSWORD=''


fosapi = FortiOSAPI()
fosapi.https('on')
fosapi.login(FGT_HOST, FGT_USER, FGT_PASSWORD)

print(fosapi.license())

fosapi.logout()
```

I use the Fortigate-60D with the Firmware v.5.2.11 and fortisapi with 0.9.

**Comment by barbosm** [comment]
Not reproducible with FG-81E and FOS 6.0.2.

Most likely than not there was some change on the API structure since 5.2 that is the root-cause of this error.

**Comment by mamunozgonzalez** [comment]
I think I saw a similar error on v5.2. Can you confirm the version? 

The library supports from 5.6 and later.

**Comment by thomnico** [comment]
The library was started with 5.4 support. Please check the 1.0rc branch as the licensing is much better handled there.

**Comment by thomnico** [comment]
#28 resolve this normally.
