### ISSUE TITLE
FortiOSAPI needs to allow selective TLS Verification

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/fortiosapi#26]
In testing of our ansible playbooks, using `ansible_fgt_modules/v6.0.2/firewall/fortios_firewall_vip.py` we hit an issue trying to act against a firewall deployed using the FortiNet A-A HA Cluster in Azure, because we were trying to use the HTTPS management interface, not an HTTP interface. We received an error message as follows:

```
"module_stderr": "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)
```

I believe it should be possible, from reading the fortiosapi code, to specify HTTPS with specific CA verification, with no verification, or to default to standard certificates. Would it be possible to have a feature flag (like you currently have with `HTTPS: bool`) to select TLS verification?

If this could also be pushed out to the Ansible modules, this would be very helpful!

Happy to engage with your support teams to help progress this.

PS. I have partner status, and am happy to liaise via our SE if required :)

**Comment by JonTheNiceGuy** [comment]
Scratch this one - I'd made a typo! :)

**Comment by thomnico** [comment]
@JonTheNiceGuy I plan to fix that (CA and client cert) in the API 
I recently add the api token login and better handling of license expiration. see v1.0rc branch and have a bit more patience

**Comment by JonTheNiceGuy** [comment]
HUZZAH! Thanks for your work on this! Are these the modules which are slowly making their way into mainline Ansible? I've had one colleague draw my attention to [the devel fortios_firewall_vip documentation](https://docs.ansible.com/ansible/devel/modules/fortios_firewall_vip_module.html#fortios-firewall-vip-module) and he asked whether he should be targetting that...

**Comment by thomnico** [comment]
Absolutely. fortiosapi is used in both upstreams (we are commiters) and in 40ansible
