### ISSUE TITLE
v1.0.1 commit is not present in master

### ISSUE THREAD

**Issue by sbraz** [fortinet-solutions-cse/fortiosapi#52]
Hi,
It looks like you pushed the tag for v1.0.1 but you didn't push the corresponding commit in the master branch.
See https://github.com/fortinet-solutions-cse/fortiosapi/compare/master...v1.0.1.

**Comment by thomnico** [comment]
See https://github.com/fortinet-solutions-cse/fortiosapi/releases/tag/v1.0.1
