### ISSUE TITLE
How to add New One-Time Schedule by cmdb api

### ISSUE THREAD

**Issue by d0l1u** [fortinet-solutions-cse/fortiosapi#53]
When I use the python code as below, then I get a error:
```
name = str(name)
        payload = {'json':
                    {
                    'name':  name ,
                    'start': stime,
                    'end': etime,
                    'type':  'One Time'
                    }
               }
        requests.post('https://$ip/api/v2/cmdb/firewall/schedule/onetime/' + name + '/', json.loads(payload))
```
the return error code is 400. So how can i use the api to create one-time schedule . Thanks!

**Comment by thomnico** [comment]
Hello,

This code can not be related to this library and you are looking a using the fortigate API directly.
It is in the doc that the site for those type of inquiries is https://fndn.fortinet.net
