### ISSUE TITLE
local variable 'mkey' referenced before assignment

### ISSUE THREAD

**Issue by xruth** [fortinet-solutions-cse/fortiosapi#54]
Ran into an issue with this line when the master key could not be retrieved:
https://github.com/fortinet-solutions-cse/fortiosapi/blob/9552a048956a68cbaf017d0f116b73bbb4a772e7/fortiosapi/fortiosapi.py#L236

In this case the variable mkey is not assigned. UnboundLocalError: local variable 'mkey' referenced before assignment.

**Comment by Akasurde** [comment]
@thomnico We can close this issue, since https://github.com/fortinet-solutions-cse/fortiosapi/pull/60 handles this error.
