### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by lijingffff** [fortinet-solutions-cse/fortiosapi#69]
Installed /usr/local/lib/python3.6/site-packages/fortiosapi-1.0.4-py3.6.egg
Processing dependencies for fortiosapi==1.0.4
Searching for oyaml
Reading https://pypi.org/simple/oyaml/

hello，
I found that downloading oyaml stopped during use. Is the wrong path for specifying **oyaml**? I noticed that **oyaml** was last updated a year ago

**Comment by thomnico** [comment]
Can you share information that allow to reproduce ?

System, cli etc .. virtualenv.

I never had a problem with this..
