### ISSUE TITLE
How to use POST module for objects under monitor (eg monitor/geoip

### ISSUE THREAD

**Issue by teguhasiong** [fortinet-solutions-cse/fortiosapi#70]
I am currently testing using restapi utilizing the fortiosapi, however, I would like to ask because I bump into issue when I am trying to monitor/geoip that must use POST.
 
In this /geoip/geoip-query/select, the fndn mentioned is using POST. Meanwhile if I am using FortiOSAPI.monitor:

    def monitor(self, path, name, vdom=None, mkey=None, parameters=None):
        url = self.mon_url(path, name, vdom, mkey)
        LOG.debug("in monitor url is %s", url)
        res = **self._session.get**(url, params=parameters, timeout=self.timeout)
        LOG.debug("in MONITOR function")
 
The procedure is using get, and can’t use POST as recommended by fndn.fortinet.
 
In the other hand, I also can not use post module :

def post(self, path, name, data, vdom=None,
             mkey=None, parameters=None):
        # we always post to the upper name/path the mkey is in the data.
        # So we can ensure the data set is correctly filled in case mkey is passed.
        LOG.debug("in POST function")
        if mkey:
            mkeyname = self.get_mkeyname(path, name, vdom)
            LOG.debug("in post calculated mkeyname : %s mkey: %s ",
                      mkeyname, mkey)
            # if mkey is forced on the function call then we change it in the data
            # even if inconsistent data/mkey is passed
            data[mkeyname] = mkey
        # post with mkey will return a 404 as the next level is not there yet
        # we pushed mkey in data if needed.
        url = **self.cmdb_url(**path, name, vdom, mkey=None)
 
Because post module will use cmdb_url , meanwhile the monitor/geoip is not under /api/v2/cmdb/.

Or should I use other procedure to accomplish POST under MONITOR/GEOIP ?
Thanks

**Comment by thomnico** [comment]
Hello the function you are looking for is called "execute" it will post to monitor. I fix the doc thanks to your report.
Please see latest version.
