### ISSUE TITLE
Fortigate 6.0.10 compatibility

### ISSUE THREAD

**Issue by killua1517** [fortinet-solutions-cse/fortiosapi#72]
Hi,
Is this version os fortiosapi compatible with a fortigate in 6.0.10 firmware version?

Thank you!

**Comment by killua1517** [comment]
Hi, Sorry for my insistence, but can help me someone with this question?

Thank you so much

**Comment by mamunozgonzalez** [comment]
Hi @killua1517,
yes, it is compatible. The functions are generic and should work with any recent version of FGT, including 6.0, 6.2, 6.4 and later versions.
