### ISSUE TITLE
Error creating groups

### ISSUE THREAD

**Issue by killua1517** [fortinet-solutions-cse/fortiosapi#73]
Hi all!
I have a problem with the fortiosapi.
When I try to create a group with the new fortiosapi version, I receive the follow message:
> Creating groups and objects for category test
   >>> Processing group 1 (0 to 500) ...

No handlers could be found for logger "fortiosapi"

And the group is not created.

I've revised the script but I can't found the error. 

Can someone help me?
Thank you so much

**Comment by thomnico** [comment]
Hello there,

Can you share the code for the missing call, version of Fortigate you are using?

In short an explanation of how to reproduce.

**Comment by killua1517** [comment]
Hello!

This is the block of script code for create groups:
`# CREATE OBJECTS AND GROUPS
    if verbose or debug:
        print('> Creating groups and objects for category %s' % category)

    tmpstr2 = 'Updated: ' + datetime.strftime(datetime.now(),"%Y/%m/%d %H:%M")
    ptr = 0
    offset = group_max_addr
    sub = None
    obj_count = 1
    grpmembers = None
    policy_mult = 0
    policy_group = []
    policy_index = 0
    if not policy_only:
        vipmembers = None

    for subcount in range(1,groups+1):
        if verbose or debug:
            print('   >>> Processing group %s (%s to %s) ...' %(subcount,ptr,offset))

        sub = ips[ptr:offset]
        grpmembers = []
        if not policy_only:
            vipmembers = []

        for member in sub:
            addrname = 'addr-' + namestr + '-' + category + str(obj_count)
            item = {
                'name' : addrname,
                'subnet' : member + ' 255.255.255.255',
                'comment' : tmpstr2,
                'visibility' : 'disable'
            }
            #if debug:
                #print('   *** Creating address %s (%s) ...' %(addrname,item['subnet']))
            # SAFE
            fwp.set('firewall', 'address', vdom='root', data=item)
            obj_count += 1

            grpmembers.append({'name':addrname})
            if not policy_only:
                vipmembers.append({'range':member})


        curr_grp = 'addrgrp-' + namestr + '-' + category + str(subcount)
        if debug:
            print('   *** Creating address group %s ...' % curr_grp)
        grp = {
            'name' : curr_grp,
            'member' : grpmembers,
            'comment' : tmpstr2
        }
        # SAFE
        fwp.set('firewall', 'addrgrp', vdom='root', data=grp)`

I use the 6.0.10 fortigate version


When I launch the script who call the fortiosapi, it create the addresses propertly and should be to create the groups.
The prompt shows the group is created, but it's false, there is nothing in the fortigate) and then shows the message: 
No handlers could be found for logger "fortiosapi"

**Comment by thomnico** [comment]
can you try to create the group before adding members to it? 

Regarding the handler, you can see an example here: https://github.com/fortinet-solutions-cse/fortiosapi-examples/blob/master/address.py on how to use it.

**Comment by killua1517** [comment]
Thank you!
But, I tried to create the group before and the result is the same.
The script creates the addresses, but not the group and not adding it in the policies.

I don0t understand it! hahaha

**Comment by killua1517** [comment]
Hi all!
Sorry, I continue with the error when I try to create group with my script.
I think the problem is with syntax of the groups get.

Can someone help me?

Thanks

**Comment by thomnico** [comment]
Please post the question on https://fndn.fortinet.net as it relates more to internal usage of the API than the python library
